// demo.js — guided auto-tour of every feature. Open the game with ?demo (add &lang=vi for Vietnamese captions).
// It drives the real game (keys, teleports, module test hooks) and shows a caption bar with Skip / Pause / Stop.

export function runDemo(G) {
  const { S, CTX, UI, enterZone, startGame, defaultSave, setMode, input } = G;
  const lang = () => UI.lang();
  const T = (en, vi) => ({ en, vi });
  const tx = o => (typeof o === 'string' ? o : o[lang()] || o.en);
  const $ = s => document.querySelector(s);

  // ---------- caption UI ----------
  const box = document.createElement('div'); box.id = 'demo';
  box.innerHTML = `<div class="d-top"><span class="d-step"></span><span class="d-title"></span></div><div class="d-desc"></div><div class="d-bar"><div></div></div>
    <div class="d-btns"><button data-a="pause">⏸</button><button data-a="skip">⏭</button><button data-a="speed">1×</button><button data-a="stop">✕</button></div>`;
  const css = document.createElement('style');
  css.textContent = `#demo{position:fixed;left:50%;bottom:78px;transform:translateX(-50%);width:min(680px,94vw);background:rgba(13,11,20,.9);border:1px solid #ffd45e;border-radius:12px;padding:10px 14px;z-index:40;color:#f2ebe0;font:14px "Segoe UI",system-ui,sans-serif;box-shadow:0 8px 30px rgba(0,0,0,.6)}
  #demo .d-top{display:flex;gap:10px;align-items:baseline}#demo .d-step{color:#ffd45e;font-weight:800;font-size:12px}#demo .d-title{font-weight:800;font-size:16px}
  #demo .d-desc{color:#cfc6b8;margin:3px 0 6px;min-height:18px}#demo .d-bar{height:4px;background:#2b2440;border-radius:2px;overflow:hidden}#demo .d-bar>div{height:100%;background:#ffd45e;width:0}
  #demo .d-btns{position:absolute;right:10px;top:8px;display:flex;gap:6px}#demo .d-btns button{border:1px solid #33294a;background:#241e34;color:#f2ebe0;border-radius:6px;padding:3px 8px;cursor:pointer;font:inherit}
  #demo.done{border-color:#7fd14b}`;
  document.head.appendChild(css); document.body.appendChild(box);
  const ui = { step: box.querySelector('.d-step'), title: box.querySelector('.d-title'), desc: box.querySelector('.d-desc'), bar: box.querySelector('.d-bar>div') };
  const st = { i: 0, paused: false, skip: false, stop: false, speed: 1 };
  box.querySelector('.d-btns').onclick = e => {
    const a = e.target.dataset.a; if (!a) return;
    if (a === 'pause') { st.paused = !st.paused; e.target.textContent = st.paused ? '▶' : '⏸'; }
    if (a === 'skip') st.skip = true;
    if (a === 'speed') { st.speed = st.speed === 1 ? 2 : 1; e.target.textContent = st.speed + '×'; }
    if (a === 'stop') { st.stop = true; st.skip = true; }
  };
  const say = (d) => { ui.desc.textContent = tx(d); };

  // ---------- helpers ----------
  const sleep = ms => new Promise(r => setTimeout(r, ms));
  async function wait(s) { const end = performance.now() + s * 1000 / st.speed; while (performance.now() < end) { if (st.skip || st.stop) return; if (st.paused) { await sleep(100); continue; } await sleep(50); } }
  async function until(fn, s = 20) { const end = performance.now() + s * 1000; while (performance.now() < end) { if (st.skip || st.stop) return false; try { if (fn()) return true; } catch (e) { } await sleep(80); } return false; }
  function keyDown(code) { window.dispatchEvent(new KeyboardEvent('keydown', { code, key: code.replace('Key', '').toLowerCase(), bubbles: true })); }
  function keyUp(code) { window.dispatchEvent(new KeyboardEvent('keyup', { code, key: code.replace('Key', '').toLowerCase(), bubbles: true })); }
  async function key(code, times = 1, gap = 0.25) { for (let i = 0; i < times; i++) { keyDown(code); await sleep(40); keyUp(code); await wait(gap); if (st.skip || st.stop) return; } }
  async function walk(dir, s) { input[dir] = true; await wait(s); input[dir] = false; }
  const tp = (x, y) => { S.player.x = x * 16 + 8; S.player.y = y * 16 + 14; };
  async function goZone(id) { if (S.zone.id === id) return; enterZone(id, 'default'); await wait(1.2); }
  async function talkOut(gap = 1.4) { for (let i = 0; i < 24 && S.mode !== 'play'; i++) { if (st.skip || st.stop) break; await key('KeyE', 1, gap); } }
  async function closePanels() { for (let i = 0; i < 4 && S.mode !== 'play'; i++) { keyDown('Escape'); await sleep(40); keyUp('Escape'); await sleep(200); } }
  const obj = pred => S.map.objects.find(pred);
  async function goObj(o, dy = 1) { if (!o) return false; const d = CTX.O[o.type]; tp(o.x + Math.floor(d.fw / 2), o.y + d.fh - 1 + dy); await wait(0.5); return true; }
  async function nearAndE(pred, dy = 1) { const o = obj(pred); if (!(await goObj(o, dy))) return false; await key('KeyE', 1, 0.5); return true; }
  const npcs = () => S.npcs.filter(n => !n.m.guide);
  async function goNpc(n) { if (!n) return; n.goal = null; n.busy = true; S.player.x = n.x - 14; S.player.y = n.y; await wait(0.5); }
  async function clickBtn(re, root = document) { const b = [...root.querySelectorAll('button')].find(b => re.test(b.textContent) && !b.disabled && b.offsetParent !== null); if (b) { b.click(); await wait(0.6); return true; } return false; }
  const meetAll = () => { for (const n of npcs()) if (!S.save.met.includes(n.m.id)) S.save.met.push(n.m.id); };
  async function quizAuto() {
    for (let i = 0; i < 8 && S.mode === 'quiz'; i++) {
      const q = $('#q-text').textContent, all = S.lore.library.concat(S.lore.elders), item = all.find(x => x.q.en === q || x.q.vi === q);
      if (item) { const corr = item.a[item.c][lang()] || item.a[item.c].en; const b = [...document.querySelectorAll('.qopt')].find(b => b.textContent.includes(corr)); b && b.click(); }
      await wait(1.6); const n = $('#q-next'); if (n && !n.hidden) n.click(); await wait(0.8);
    }
  }
  const parked = () => (window.__veh && __veh.info().parked) || null;
  async function mountParked(walkDir, s) {
    const p = parked(); if (!p) return false;
    tp(p.x, p.y + 1); await wait(0.4); if (!S.near) { tp(p.x - 1, p.y); await wait(0.4); }
    await key('KeyE', 1, 0.6); if (walkDir) await walk(walkDir, s); return true;
  }
  const raidState = () => (window.__raidLowState && S.zone.order <= 3 ? __raidLowState() : window.__raidMidState && S.zone.order <= 6 ? __raidMidState() : null);
  async function goPlotCenter(i) { const p = S.map.plots[i]; if (p) tp(p.x + 5, p.y + 4); await wait(0.4); }

  // ---------- the tour ----------
  const steps = [
    { t: T('Welcome', 'Chào mừng'), d: T('This tour plays the game by itself. ⏭ skips a step, ⏸ pauses, ✕ stops.', 'Tour này tự chơi. ⏭ bỏ qua bước, ⏸ tạm dừng, ✕ dừng hẳn.'), run: async () => { await wait(3); } },
    // ---- the story: Lyron at sea (act 1) ----
    { t: T('Story · adrift, then Lyron', 'Cốt truyện · chơi vơi, rồi Lyron'), d: T('You wake on a plank with no paddle. A raft with a torn sail finds you — Lyron, the founder of Seismic, pulls you aboard.', 'Bạn tỉnh dậy trên mảnh ván, không chèo được. Một chiếc bè buồm rách tìm thấy bạn — Lyron, nhà sáng lập Seismic, kéo bạn lên.'), run: async () => { if (!window.__storySea) return; await goZone('sea'); await wait(3); __storySea.skipWait(); await until(() => S.mode === 'dialog', 12); await talkOut(1.6); await wait(2.5); } },
    { t: T('Story · the Kraken takes Lyron', 'Cốt truyện · Kraken bắt Lyron'), d: T('In sight of the lighthouse the Kraken rises. Lyron pushes you onto a plank and cuts the rope. His scarf floats back up.', 'Thấy hải đăng rồi thì Kraken trồi lên. Lyron đẩy bạn lên mảnh ván rồi cắt dây. Chiếc khăn của cậu ấy nổi lại.'), run: async () => { if (!window.__storySea) return; __storySea.completeAll(); __storySea.warp(42, 44); await wait(0.5); __storySea.climax(); await until(() => S.mode === 'dialog', 10); await talkOut(1.6); await until(() => CTX.story().act >= 2, 20); await wait(4); await until(() => CTX.story().keepsake || S.zone.id !== 'sea', 10); await wait(1); } },
    // ---- the Sea of Origins (every new game starts here) ----
    { t: T('Sea of Origins · adrift', 'Biển Khởi Nguồn · lênh đênh'), d: T('You wake on a ragged raft. Arrows on the water are currents — ride them towards the lighthouse.', 'Bạn tỉnh dậy trên bè rách. Mũi tên trên nước là hải lưu — xuôi dòng về phía hải đăng.'), run: async () => { enterZone('sea', 'default'); await wait(2.5); await walk('down', 2.5); await walk('right', 1.5); } },
    { t: T('Sea · planks, patching, the sail', 'Biển · ván, vá bè, buồm'), d: T('Floating planks patch the raft (it has HP). Sailcloth from the wreck + rope → raise a sail, 2× faster.', 'Ván trôi để vá bè (bè có HP). Vải buồm từ xác tàu + dây → giương buồm, nhanh gấp đôi.'), run: async () => { if (!window.__raft) return; __raft.give(); __raft.damage(2); __raft.warp(40, 12); await wait(0.8); for (let i = 0; i < 2; i++) { if (S.near && /Patch|Vá/.test(S.near.label || '')) { await key('KeyE', 1, 1.2); break; } await wait(0.5); } await wait(0.5); if (S.near && /sail|buồm/i.test(S.near.label || '')) await key('KeyE', 1, 1.5); await walk('left', 2); } },
    { t: T('Sea · whirlpool', 'Biển · xoáy nước'), d: T('It pulls the raft in and spins it — mash E to break free, or lose what is on your head.', 'Xoáy hút bè vào và quay tròn — bấm E liên tục để thoát, không thì mất đồ trên đầu.'), run: async () => { if (!window.__raft) return; const w = __raft.info().whirls[0]; if (!w) return; __raft.warp(w.x, w.y - 2); await wait(2.5); for (let i = 0; i < 14; i++) { if (!__raft.info().caught) break; await key('KeyE', 1, 0.22); } await wait(2); } },
    { t: T('Sea · diving the reef', 'Biển · lặn rạn san hô'), d: T('Bright water hides shells, pearls and sea crystals. 12 s of air — and a shark hunts divers.', 'Nước sáng màu giấu vỏ sò, ngọc trai, tinh thể biển. 12 giây dưỡng khí — và cá mập săn thợ lặn.'), run: async () => { if (!window.__dive || !window.__raft) return; const sp = __dive.spots().find(p => p.items.length >= 3) || __dive.spots()[0]; if (!sp) return; __raft.warp(sp.cx, sp.cy); await wait(0.8); if (S.near && /Dive|Lặn/.test(S.near.label || '')) await key('KeyE', 1, 1); for (const it of sp.items.slice(0, 3)) { if (!__dive.dive()) break; tp(it.tx, it.ty); await wait(0.9); } if (__dive.dive()) { const p = S.player; __dive.warpShark(Math.floor(p.x / 16) + 4, Math.floor(p.y / 16)); await wait(4); } await closePanels(); await wait(1); } },
    { t: T('Sea · fishing from the raft', 'Biển · câu cá trên bè'), d: T('Schools drift under the raft; hot spots bite fast. Squid and a rare golden fish live here.', 'Đàn cá trôi dưới bè; điểm dày cắn nhanh. Có mực và cá vàng hiếm.'), run: async () => { if (!window.__dive || !window.__raft) return; CTX.tool.set('rod', 1); const sc = __dive.schools().find(s => s.hot) || __dive.schools()[0]; if (sc) __raft.warp(Math.round(sc.tx) - 2, Math.round(sc.ty)); S.player.dir = 2; await wait(0.8); if (!(S.near && /Cast|Thả/.test(S.near.label || ''))) { await walk('right', 0.3); await wait(0.4); } await key('KeyE'); await until(() => __dive.fishing() && __dive.fishing().phase === 'bite', 22); await key('KeyE'); for (let i = 0; i < 80; i++) { const f = __dive.fishing(); if (!f || S.mode === 'play') break; await key('KeyE', 1, 0.2); } await wait(2); } },
    { t: T('Sea · castaways & bottles', 'Biển · người trôi dạt & chai thư'), d: T('Real artists cling to driftwood — pull them aboard and bring them to the pier. Bottles carry their notes.', 'Nghệ sĩ thật bám mảnh gỗ — kéo lên bè, chở về bến. Chai thư mang lời nhắn của họ.'), run: async () => { if (!window.__life || !window.__raft) return; const c = __life.castaways()[0]; if (c) { __raft.warp(c.tx - 1, c.ty); await wait(0.8); await key('KeyE', 1, 1.2); } const b = __life.bottles().find(b => !b.taken); if (b) { __raft.warp(b.tx, b.ty); await wait(1.5); await talkOut(1.4); } if (c) { __raft.warp(42, 53); await wait(1.5); await talkOut(1.4); } } },
    { t: T('Sea · the whale', 'Biển · cá voi'), d: T('When a whale surfaces, sail alongside and ride it across the sea.', 'Cá voi nổi lên thì áp bè lại, cưỡi nó băng qua biển.'), run: async () => { if (!window.__life || !window.__raft) return; __raft.warp(40, 20); await wait(0.5); __life.summonWhale(); await wait(1.5); await walk('right', 0.8); await wait(0.5); for (let i = 0; i < 6; i++) { if (S.near && /whale|cá voi/i.test(S.near.label || '')) { await key('KeyE', 1, 1); break; } await walk('right', 0.3); } await wait(13); } },
    { t: T('Sea · the Kraken', 'Biển · Kraken'), d: T('The destroyer of the sea: tentacles smash the raft. Strike each twice, feed it a fish, or flee down a current.', 'Kẻ phá vùng biển: xúc tu đập bè. Đánh mỗi xúc tu 2 phát, ném cá cho nó, hoặc chạy theo hải lưu.'), run: async () => { if (!window.__seaRaid || !window.__raft) return; __raft.warp(40, 20); await wait(0.5); __seaRaid.kraken(); await wait(5); for (let i = 0; i < 5; i++) { const k = __seaRaid.state().kraken; if (!k) break; const t = k.tents.find(t => t.hp > 0 && t.st !== 'dead'); if (!t) break; S.player.x = t.x - 14; S.player.y = t.y + 6; await wait(0.6); await key('KeyE', 2, 0.6); } await wait(3); } },
    { t: T('Sea · the ghost ship', 'Biển · tàu ma'), d: T('Pirates board you at night and take stones. With rope, grapple it first and loot its hold.', 'Đêm xuống hải tặc ma cướp đá. Có dây thì móc tàu trước và lục khoang kho báu.'), run: async () => { if (!window.__seaRaid || !window.__raft) return; CTX.bag.add('rope', 1); __raft.warp(40, 24); await wait(0.5); __seaRaid.ship(); const ok = await until(() => S.near && /Grapple|Móc/.test(S.near.label || ''), 8); if (ok) { await key('KeyE', 1, 1.2); const b = document.querySelector('#gs-chests button'); if (b) { b.click(); await wait(3); } } else await wait(4); await closePanels(); } },
    { t: T("Sea · the hermit's buoy race", 'Biển · đua phao của ẩn sĩ'), d: T('A real artist lives on the middle island. Round the 6 buoys under 150 s to become Captain.', 'Một nghệ sĩ thật sống trên đảo giữa. Qua 6 phao dưới 150 giây để thành Thuyền trưởng.'), run: async () => { if (!window.__life || !window.__raft) return; __raft.warp(40, 31); S.player.dir = 3; await wait(0.8); if (S.near && /Step off|Bước lên/.test(S.near.label || '')) await key('KeyE', 1, 0.8); const h = S.npcs.find(n => n.hermit); if (h) { await goNpc(h); await key('KeyE'); await until(() => S.mode !== 'dialog', 6); for (let i = 0; i < 6 && !document.querySelector('#sl-start'); i++) await key('KeyE', 1, 1); await clickBtn(/Start|Bắt đầu/); } await wait(1); const pk = __raft.info().parked; if (S.sea && S.sea.riding !== 'raft' && pk) { tp(pk.x, pk.y - 1); await wait(0.5); if (S.near && /Board|Lên bè/.test(S.near.label || '')) await key('KeyE', 1, 0.8); } if (!S.sea || S.sea.riding !== 'raft') { await wait(2); return; } const r = __life.race(); for (const b of (r && r.buoys) || []) { __raft.warp(b.x, b.y + 1); await wait(0.9); } await wait(3); } },
    { t: T('Sea · the lighthouse pier', 'Biển · cầu tàu hải đăng'), d: T('Gentle nights make lamps glow; the beam points home. Step off at the pier — Harbor Village is right behind.', 'Đêm nhẹ làm đèn tỏa sáng; tia hải đăng chỉ về nhà. Rời bè ở cầu tàu — Làng ngay sau lưng.'), run: async () => { if (!window.__raft) return; await closePanels(); if (S.sea && S.sea.riding === 'raft') { __raft.warp(40, 46); await wait(0.5); await walk('down', 1.5); await wait(0.3); if (S.near && /Step off|Bước lên/.test(S.near.label || '')) await key('KeyE', 1, 0.8); } if (!S.sea || S.sea.riding !== null) tp(40, 57); await wait(0.3); await walk('down', 2.2); await until(() => S.zone.id === 'village', 6); if (S.zone.id !== 'village') await goZone('village'); await wait(1.5); } },
    { t: T('Harbor Village — the guide', 'Làng Xuất Phát — hướng dẫn viên'), d: T('Talking to Noxx, the community manager.', 'Nói chuyện với Noxx, CM của Seismic.'), run: async () => { if (S.guide) { S.player.x = S.guide.x - 14; S.player.y = S.guide.y; await wait(0.5); await key('KeyE'); await talkOut(1.8); } } },
    { t: T('Meet a real artist', 'Gặp một nghệ sĩ thật'), d: T('Every NPC is a member of #artwork — avatar, stats and a tremor shard.', 'Mỗi NPC là thành viên #artwork — avatar, thống kê, +1 mảnh dư chấn.'), run: async () => { await goNpc(npcs()[0]); await key('KeyE'); await talkOut(1.8); } },
    { t: T('Nation board', 'Bảng thành tựu quốc gia'), d: T('Medals, top artists and the district tier.', 'Huy chương, top nghệ sĩ, bậc khu.'), run: async () => { await nearAndE(o => o.piece === 'board' && !o.rocky); await wait(4); await closePanels(); } },
    { t: T('Rocky statue', 'Tượng Rocky'), d: T('Each nation raises its own Rocky, grander in higher lands.', 'Mỗi nước có tượng Rocky riêng, vùng cao càng đẹp.'), run: async () => { const o = obj(o => o.rocky); await goObj(o, 1); await wait(2.5); } },
    { t: T('Photo mode (P)', 'Chế độ chụp ảnh (P)'), d: T('Frame yourself with the artists and Rocky, add a sticker and download a PNG to share.', 'Đóng khung mình với nghệ sĩ và Rocky, thêm nhãn, tải PNG để khoe.'), run: async () => { if (!window.__photo) return; const o = obj(o => o.rocky); await goObj(o, 1); await key('KeyP'); await wait(1); __photo.set({ frame: 'polaroid', sticker: 'me', filter: 'warm', wave: true }); await wait(3); await key('KeyE', 1, 1.5); await wait(1.5); await closePanels(); } },
    { t: T('Hall of Magnitude', 'Bia Vinh Danh'), d: T('Everyone from this land, searchable.', 'Toàn bộ thành viên vùng này, có tìm kiếm.'), run: async () => { await nearAndE(o => o.hall, 1); await wait(3.5); await closePanels(); } },
    { t: T('World map (M)', 'Bản đồ thế giới (M)'), d: T('The sea, the village and the 9 Magnitude lands; fast travel to unlocked ones.', 'Biển, Làng và 9 vùng Magnitude; dịch chuyển nhanh tới vùng đã mở.'), run: async () => { await key('KeyM'); await wait(3.5); await closePanels(); } },
    { t: T('Codex (C)', 'Sổ tay (C)'), d: T('Artists met, progress per land, achievements.', 'Đã gặp ai, tiến độ từng vùng, thành tựu.'), run: async () => { await key('KeyC'); await wait(3.5); await closePanels(); } },
    { t: T('M1 · catching animals', 'M1 · bắt thú'), d: T('Chickens and cows are caught instantly and ride on your head.', 'Gà, bò bắt là dính ngay, đội lên đầu.'), run: async () => { await goZone('m1'); await wait(1); for (const k of ['chicken', 'cow']) { if (window.__animals && __animals.warp(k, 14)) { await wait(0.5); await key('KeyE', 1, 1.2); } } } },
    { t: T('M1 · fishing', 'M1 · câu cá'), d: T('Cast near the shoal, hook on "!", then tap E steadily — mash and the line snaps.', 'Thả gần đàn cá, thấy "!" thì giật, rồi bấm E đều tay — bấm loạn là đứt cước.'), run: async () => {
      CTX.tool.set('rod', 1); const sh = window.__animals && __animals.shore(); if (!sh) return; tp(sh.tx, sh.ty); S.player.dir = sh.dir; await wait(0.6); await key('KeyE');
      await until(() => __animals.fishing() && __animals.fishing().phase === 'bite', 14); const f = __animals.fishing(); if (f && f.phase === 'wait') f.t = 0.1;
      await until(() => __animals.fishing() && __animals.fishing().phase === 'bite', 4); await key('KeyE');
      for (let i = 0; i < 80; i++) { const g = __animals.fishing(); if (!g || g.phase === 'done' || S.mode === 'play') break; await key('KeyE', 1, 0.2); } await wait(2);
    } },
    { t: T('M1 · rowing the boat', 'M1 · chèo thuyền'), d: T('The boat only moves on water; with a sail it goes 3× faster.', 'Thuyền chỉ đi trên nước; có buồm nhanh gấp 3.'), run: async () => { window.__veh && __veh.setFlags({ sail: true }); await mountParked('right', 2.2); await walk('down', 1); await walk('left', 2.6); await key('KeyE', 1, 0.6); } },
    { t: T('Trader', 'Thương nhân'), d: T('Sell what is on your head for Seismic stones.', 'Bán thú trên đầu lấy đá Seismic.'), run: async () => { await nearAndE(o => o.trader); await wait(1.5); await clickBtn(/Sell all|Bán hết/); await wait(1.5); await closePanels(); } },
    { t: T('M2 · market outfits', 'M2 · chợ trang phục'), d: T('Trade tremor shards for a new look.', 'Đổi mảnh dư chấn lấy áo/tóc.'), run: async () => { await goZone('m2'); S.save.shards += 6; await nearAndE(o => o.shop); await wait(1.2); const sw = document.querySelectorAll('.sw[data-part="shirt"]')[1]; sw && sw.click(); await wait(1.5); await closePanels(); } },
    { t: T('M2 · sheep & wool', 'M2 · cừu và len'), d: T('Shear a sheep with a knife.', 'Xén lông cừu bằng dao.'), run: async () => { CTX.tool.set('knife', 1); if (window.__eco && __eco.warp('sheep', 14)) { await wait(0.5); await key('KeyE', 1, 1.5); } } },
    { t: T('M2 · taming a horse', 'M2 · thuần ngựa'), d: T('Feed hay three times, saddle up, ride at 1.8× with a bigger bag.', 'Cho ăn rơm 3 lần, đóng yên, cưỡi nhanh 1,8× và túi rộng hơn.'), run: async () => { CTX.bag.add('hay', 3); CTX.tool.set('saddle', 1); if (!(window.__eco && __eco.warp('horse', 14))) return; await wait(0.5); await key('KeyE', 3, 1.2); await wait(0.5); __eco.warp('horse', 14); await wait(0.3); await key('KeyE', 1, 0.8); await walk('right', 1.5); await walk('up', 1.5); await key('KeyE', 1, 0.6); } },
    { t: T('M3 · chopping a tree', 'M3 · chặt cây'), d: T('Three swings → wood and a stump.', 'Ba nhát → gỗ, để lại gốc.'), run: async () => { await goZone('m3'); const p = S.player; const t = S.map.objects.filter(o => o.type === 'tree').sort((a, b) => Math.hypot(a.x * 16 - p.x, a.y * 16 - p.y) - Math.hypot(b.x * 16 - p.x, b.y * 16 - p.y))[0]; await goObj(t, 1); await key('KeyE', 3, 0.7); await wait(1); } },
    { t: T('M3 · campfire & berries', 'M3 · đốt lửa & hái quả'), d: T('Light the cold campfires (land task) and pick ripe berries.', 'Đốt đống lửa tắt (nhiệm vụ vùng) và hái quả chín.'), run: async () => { await nearAndE(o => o.fire && !o.lit); await wait(1); await nearAndE(o => o.type === 'bush'); await wait(1.5); } },
    { t: T('M3 · planting a seed', 'M3 · trồng hạt'), d: T('Seeds grow into real trees in three stages.', 'Hạt lớn thành cây thật qua 3 giai đoạn.'), run: async () => { CTX.bag.add('seed', 2); const m = S.map; for (let y = 22; y < 40 && S.mode === 'play'; y++) { const x = 20; if (CTX.getG(m, x, y) === CTX.T.GRASS && !CTX.isSolid(m, x, y) && !m.roads[y * m.w + x] && CTX.plotAt(x, y) < 0) { tp(x, y); await wait(0.5); if (S.near && /Plant|Trồng/.test(S.near.label || '')) { await key('KeyE', 1, 1.5); const pl = S.save.sys.gather?.plants?.m3; if (pl && pl[0]) pl[0].t0 -= 70000; await wait(2); break; } } } } },
    { t: T('M3 · honey', 'M3 · mật ong'), d: T('A torch keeps the bees calm.', 'Có đuốc thì ong không đốt.'), run: async () => { CTX.tool.set('torch', 1); await nearAndE(o => o.type === 'beehive', 1); await wait(2); } },
    { t: T('M3 · art dealer', 'M3 · nhà buôn tranh'), d: T('Wood buys an artist\'s card for your collection.', 'Gỗ đổi thẻ tranh của nghệ sĩ.'), run: async () => { CTX.bag.add('wood', 12); await nearAndE(o => o.dealer); await wait(1.2); await clickBtn(/^Buy|^Mua/); await wait(1.2); await clickBtn(/collection|Bộ sưu tập/); await wait(2.5); await closePanels(); } },
    { t: T('Quests (Q)', 'Nhiệm vụ (Q)'), d: T('Artists ask for things; hand in for stones and cards.', 'Nghệ sĩ nhờ việc; giao xong nhận đá và thẻ.'), run: async () => {
      meetAll(); if (!window.__quests) return; const n = npcs()[1]; const id = __quests.give(n.m.id, 'fetch'); await wait(0.5); await key('KeyQ'); await wait(3); await closePanels();
      const q = __quests.list().active.find(a => a.npcId === id); if (q && q.item) CTX.bag.add(q.item, q.n); await goNpc(n); await key('KeyE', 1, 0.8); await clickBtn(/Hand in|Giao/); await wait(1.5); await talkOut(1.5);
    } },
    { t: T('M4 · mining & the furnace', 'M4 · đào quặng & lò nung'), d: T('Pickaxe the ore vein, then smelt charcoal and iron.', 'Cuốc mạch quặng, rồi nung than và sắt.'), run: async () => { await goZone('m4'); CTX.tool.set('pickaxe', 1); await nearAndE(o => o.type === 'orevein'); await key('KeyE', 2, 0.7); await wait(1); CTX.bag.add('wood', 9); CTX.bag.add('ore', 4); await nearAndE(o => o.type === 'craft_furnace'); await wait(1); await clickBtn(/Craft|Chế tạo/); await wait(2.2); await clickBtn(/Craft|Chế tạo/); await wait(2.2); await closePanels(); } },
    { t: T('M4 · jeep & mine cart', 'M4 · jeep & xe goòng'), d: T('The jeep burns charcoal; the cart rides the rails at 3×.', 'Jeep tốn than; xe goòng chạy ray nhanh gấp 3.'), run: async () => { CTX.bag.add('charcoal', 3); await mountParked('up', 2); await key('KeyE', 1, 0.8); tp(40, 55); await wait(0.5); await key('KeyE', 1, 0.6); await walk('up', 2.5); await key('KeyE', 1, 0.8); } },
    { t: T('M4 · Tommyknockers', 'M4 · Quỷ mỏ'), d: T('Mine spirits wreck a yard — they fear yards with two lit torches. Strike them with the axe.', 'Quỷ mỏ phá khu — sợ khu còn 2 đuốc. Đánh bằng rìu.'), run: async () => { window.__raidMidFast = true; window.__raidMid && __raidMid(); await wait(4); const s = raidState(); if (s && s.plotIdx >= 0) await goPlotCenter(s.plotIdx); await wait(8); for (let i = 0; i < 4; i++) { const m = (raidState() || {}).mobs || []; const mob = m.find(x => x.hp > 0); if (!mob) break; S.player.x = mob.x - 12; S.player.y = mob.y; await wait(0.4); await key('KeyE', 2, 0.5); } await wait(3); } },
    { t: T('M5 · levers & the fault bridge', 'M5 · cần gạt & cầu qua vực'), d: T('Both levers raise the bridge across the fault.', 'Gạt 2 cần để cầu nâng lên.'), run: async () => { await goZone('m5'); for (const o of S.map.objects.filter(o => o.lever)) { await goObj(o, 1); await key('KeyE', 1, 1); } tp(40, 32); await wait(0.3); await walk('up', 2.5); } },
    { t: T('M5 · sandworm', 'M5 · sâu cát'), d: T('It rises from the fault and swallows walls — drop a live animal as bait.', 'Trồi từ đứt gãy nuốt tường — thả thú sống làm mồi.'), run: async () => { const c = CTX.carry.get(); if (!c.length) { c.push('chicken'); S.save.inv.chicken = 1; } window.__raidMidFast = true; window.__raidMid && __raidMid(); await wait(4); const s = raidState(); if (s && s.plotIdx >= 0) await goPlotCenter(s.plotIdx); await wait(9); const m = ((raidState() || {}).mobs || [])[0]; if (m) { S.player.x = m.x - 16; S.player.y = m.y; await wait(0.5); await key('KeyE', 1, 1); } await wait(3); } },
    { t: T('M6 · library exam', 'M6 · thi thư viện'), d: T('Five questions about Seismic, each with a source link.', 'Năm câu về Seismic, mỗi câu có link nguồn.'), run: async () => { await goZone('m6'); await nearAndE(o => o.quiz); await wait(1); await quizAuto(); await wait(1.5); } },
    { t: T('M6 · gargoyles', 'M6 · gargoyle'), d: T('Stone statues come alive; they can only be hit inside lantern light.', 'Tượng đá sống dậy; chỉ đánh được trong ánh đèn lồng.'), run: async () => { window.__raidMidFast = true; window.__raidMid && __raidMid(); await wait(4); const s = raidState(); if (s && s.plotIdx >= 0) await goPlotCenter(s.plotIdx); await wait(12); } },
    { t: T('M7 · lava & obsidian', 'M7 · dung nham & obsidian'), d: T('An iron bucket scoops lava; obsidian veins need an iron pickaxe.', 'Xô sắt múc dung nham; obsidian cần cuốc sắt.'), run: async () => { await goZone('m7'); CTX.tool.set('bucket', 2); CTX.tool.set('pickaxe', 2); const m = S.map; outer: for (let y = 16; y < 22; y++) for (let x = 10; x < 70; x++) if (CTX.getG(m, x, y) === CTX.T.LAVA && !CTX.isSolid(m, x, y + 1) && !m.objects.some(o => o.x === x && o.y === y + 1)) { tp(x, y + 1); S.player.dir = 3; break outer; } await wait(0.6); await key('KeyE', 1, 2); await nearAndE(o => o.type === 'obsvein'); await key('KeyE', 2, 0.7); await wait(1); } },
    { t: T('M7 · the fire drake', 'M7 · Hỏa Long'), d: T('Throw Seismic stones at it (4 hits). Rocky is immune to its fire.', 'Ném đá Seismic (4 phát). Rocky miễn nhiễm lửa.'), run: async () => { CTX.bag.add('stone', 12); window.__raidHighFast = true; const r = window.__raidHigh && __raidHigh(); await wait(5); const ps = S.map.plots; if (r && r.plotIdx >= 0 && ps[r.plotIdx]) await goPlotCenter(r.plotIdx); await wait(6); for (let i = 0; i < 6; i++) { if (S.near && /stone|đá/i.test(S.near.label || '')) await key('KeyE', 1, 0.6); else await wait(0.6); } await wait(3); } },
    { t: T('M8 · skis, wax & the balloon', 'M8 · ván trượt, sáp & khinh khí cầu'), d: T('Waxed skis fly over snow; the balloon crosses anything for 20 s.', 'Ván bôi sáp lướt tuyết; khinh khí cầu bay qua mọi thứ 20 giây.'), run: async () => { await goZone('m8'); window.__veh && __veh.setFlags({ wax: true, sail: true }); await mountParked('up', 2.5); await key('KeyE', 1, 0.8); CTX.bag.add('charcoal', 3); const b = obj(o => o.type === 'veh_balloon'); if (b) { await goObj(b, 1); await key('KeyE', 1, 1.5); await walk('left', 3); await walk('down', 2); await key('KeyE', 1, 1.5); } } },
    { t: T('M8 · the Yeti', 'M8 · Yeti'), d: T('It punches walls and starts avalanches — offer it a fish and it leaves.', 'Nó đấm tường, gây lở tuyết — cho cá thì bỏ đi.'), run: async () => { const c = CTX.carry.get(); if (!c.some(x => (typeof x === 'string' ? x : x.kind) === 'fish')) { c.push('fish'); S.save.inv.fish = (S.save.inv.fish || 0) + 1; } window.__raidHighFast = true; const r = window.__raidHigh && __raidHigh(); await wait(5); if (r && r.plotIdx >= 0) await goPlotCenter(r.plotIdx); await wait(6); for (let i = 0; i < 8; i++) { if (S.near && /fish|cá/i.test(S.near.label || '')) { await key('KeyE', 1, 1); break; } await wait(0.7); } await wait(3); } },
    { t: T('M8 · the Elders', 'M8 · Trưởng lão'), d: T('The top three artists ask riddles about Seismic.', 'Ba nghệ sĩ hàng đầu ra câu đố về Seismic.'), run: async () => { const e = S.npcs.find(n => n.m.elder); if (!e) return; await goNpc(e); await key('KeyE'); await until(() => S.mode === 'quiz', 8) || await talkOut(1); if (S.mode !== 'quiz') { await key('KeyE', 6, 1); } await quizAuto(); await wait(1.5); } },
    { t: T('M9 · the Leaders & Bakunawa', 'M9 · Leader & Bakunawa'), d: T('Fifteen Leaders keep the Core. Beat the ritual drum (6 beats) to drive the serpent off.', '15 Leader giữ lõi. Gõ trống nghi lễ 6 nhịp đuổi rắn.'), run: async () => { await goZone('m9'); for (const n of S.npcs.filter(n => CTX.isLeader(n.m))) if (!S.save.met.includes(n.m.id)) S.save.met.push(n.m.id); const l = S.npcs.find(n => CTX.isLeader(n.m) && !n.m.elder); await goNpc(l); await key('KeyE'); await talkOut(1.3); if (S.mode === 'quiz') await quizAuto(); window.__raidHighFast = true; const r = window.__raidHigh && __raidHigh(); await wait(5); if (r && r.plotIdx >= 0) await goPlotCenter(r.plotIdx); await wait(5); await key('KeyE', 1, 0.8); await key('KeyE', 6, 0.32); await wait(3); } },
    { t: T('M9 · piloting Rocky', 'M9 · điều khiển Rocky'), d: T('Trusted by a nation? Spend 5 stones and become its Rocky — stomp rocks for more stones.', 'Được nước đó tin? Tốn 5 đá hóa thành Rocky — dậm đá lấy thêm đá.'), run: async () => { meetAll(); CTX.bag.add('stone', 10); const o = obj(o => o.rocky); await goObj(o, 1); await wait(0.4); await key('KeyE', 1, 1); await walk('down', 1.5); await walk('left', 3); await walk('right', 3); await key('KeyE', 1, 1); } },
    { t: T('M9 · Rocky sumo', 'M9 · sumo Rocky'), d: T("Pilot a nation's Rocky onto the dohyo and challenge another nation — shove (E) their statue over the rope.", 'Điều khiển Rocky một nước lên sàn đấu, thách nước khác — xô (E) tượng họ qua vòng dây.'), run: async () => { if (!window.__sumo) return; const r = __sumo.ring(); if (!r) return; tp(r.tx + 2, r.ty + 5); await wait(0.6); const opp = S.nations[1] || S.nations[0]; if (!opp) return; __sumo.start(opp.key, true); await wait(4.5); for (let i = 0; i < 14; i++) { const st = __sumo.state(); if (st.phase !== 'duel') break; const ai = st.ai, p = S.player; input.right = ai.x > p.x + 2; input.left = ai.x < p.x - 2; input.down = ai.y > p.y + 4; input.up = ai.y < p.y - 4; await key('KeyE', 1, 0.5); } for (const k in input) input[k] = false; if (__sumo.state().phase === 'duel') __sumo.win(); await wait(4); } },
    { t: T('M9 · the crystal egg & your Rocky pet', 'M9 · trứng tinh thể & thú cưng Rocky'), d: T('Warm the egg with 3 crystals and walk 400 tiles — a mini Rocky hatches, follows you, fetches things and gets hungry.', 'Ủ trứng bằng 3 tinh thể, đi 400 ô — Rocky con nở, theo bạn, nhặt đồ và biết đói.'), run: async () => { if (!window.__pet) return; CTX.bag.add('crystal', 3); const e = obj(o => o.type === 'crystal_egg'); if (e) { await goObj(e, 1); await key('KeyE', 1, 1.2); } __pet.hatchNow(); await wait(1.5); keyDown('Enter'); await sleep(40); keyUp('Enter'); await wait(0.6); await clickBtn(/^OK|^Xong/); await walk('left', 1.5); await walk('right', 1.5); await wait(2); __pet.fetchNow(); await until(() => __pet.state().holding, 12); await wait(0.5); const p = __pet.state().ent; if (p) { S.player.x = p.x - 14; S.player.y = p.y; await wait(0.6); await key('KeyE', 1, 1); } __pet.feed(); await wait(2); } },
    // ---- the story: the three things, the trench, the rescue ----
    { t: T('Story · the three things', 'Cốt truyện · ba vật cứu hộ'), d: T('The diving bell (M4 furnace), the trench map (M6 library) and the Great Crystal (the 15 Leaders). With all three, the pier lets you dive.', 'Chuông lặn (lò M4), bản đồ vực (thư viện M6) và Đại tinh thể (15 Leader). Đủ ba thứ, cầu tàu cho bạn lặn.'), run: async () => { if (!window.__storyLand) return; __storyLand.giveAll(); await wait(3); enterZone('sea', 'back'); await wait(1.5); if (S.sea && S.sea.riding) { const pk = __raft && __raft.info().parked; } tp(40, 55); await wait(0.6); for (let i = 0; i < 6; i++) { if (S.near && /Dive|Lặn/.test(S.near.label || '')) break; tp(40, 54 + (i % 3)); await wait(0.4); } await key('KeyE', 1, 1); await talkOut(1.4); await until(() => S.zone.id === 'trench', 8); await wait(1.5); } },
    { t: T('Story · the Kraken Trench', 'Cốt truyện · Vực Kraken'), d: T('Air runs out — breathe at the vents. Cut tentacle pillars, dodge sharks. A Rocky that trusts you follows: 1 Ground Pound · 2 Stone Shield · 3 Crush.', 'Dưỡng khí cạn dần — thở ở miệng phun. Chém xúc tu chắn đường, né cá mập. Rocky tin bạn đi theo: 1 Dậm đất · 2 Khiên đá · 3 Bóp nát.'), run: async () => { if (!window.__trench) return; if (S.zone.id !== 'trench') { CTX.story().act = 3; enterZone('trench', 'default'); await wait(1.5); } CTX.tool.set('knife', 3); __trench.giveAlly(); await wait(0.5); const pl = (__trench.state().pillars || [])[0]; if (pl && pl.x !== undefined) { tp(pl.x, pl.y + 1); await wait(0.6); await key('KeyE', 3, 0.5); } await wait(1.5); __trench.warpArena(); await wait(4); __trench.bossSkill && __trench.bossSkill('ink'); await wait(3); __trench.skill(1); await wait(2.5); __trench.skill(2); await wait(2); __trench.killTents(6); await wait(1.5); for (let i = 0; i < 3; i++) { __trench.skill(3); await wait(1.2); } await wait(2); } },
    { t: T('Story · the cage opens', 'Cốt truyện · lồng mở'), d: T('The Kraken retreats, the bubble cage pops, Lyron is free. His name opens the credits from now on.', 'Kraken rút lui, lồng bong bóng vỡ, Lyron được tự do. Từ giờ tên cậu ấy mở đầu credits.'), run: async () => { if (!window.__trench) return; if (!CTX.story().rescued) __trench.win(); await until(() => S.mode === 'dialog', 12); await talkOut(1.6); await until(() => S.mode === 'end', 6); await wait(4); await closePanels(); } },
    { t: T('Story · Lyron home', 'Cốt truyện · Lyron về làng'), d: T('Harbor Village hangs its lanterns. Lyron stays by Noxx and gives you a one-of-a-kind art card.', 'Làng Xuất Phát treo đèn. Lyron ở cạnh Noxx và tặng bạn thẻ tranh độc nhất.'), run: async () => { await goZone('village'); await wait(1); const ly = S.npcs.find(n => n.m && n.m.friend); if (ly) { await goNpc(ly); await key('KeyE', 1, 1); await talkOut(1.6); } await wait(2.5); } },
    { t: T('Districts — damage, repair, upgrade', 'Khu quốc gia — hư, sửa, nâng cấp'), d: T('A wrecked yard asks for wood and stone; the nation\'s artists rebuild it (faster at higher magnitude), then upgrade it a tier.', 'Khu hư đòi gỗ và đá; nghệ sĩ nước đó xây lại (cấp cao làm nhanh hơn), rồi nâng một bậc.'), run: async () => {
      await goZone('m3'); meetAll(); const ps = CTX.piecesOf(0); for (const w of ps.filter(o => o.piece === 'wall').slice(0, 4)) CTX.damage(w, 9); await goPlotCenter(0); await wait(3);
      CTX.bag.add('wood', 40); CTX.bag.add('stone', 40); const b = ps.find(o => o.piece === 'board'); await goObj(b, 1); await key('KeyE', 1, 1); await clickBtn(/Deliver|Giao/); await wait(1); await closePanels(); await goPlotCenter(0); await wait(14);
      await goObj(b, 1); await key('KeyE', 1, 1); await clickBtn(/Deliver|Giao/); await wait(1); await closePanels(); await goPlotCenter(0); await wait(16);
    } },
    { t: T('The Core & credits', 'Lõi & credits'), d: T('Find all 15 Leaders and the core gate opens. 3,706 names roll.', 'Tìm đủ 15 Leader thì cổng lõi mở. 3.706 cái tên chạy.'), run: async () => { await goZone('m9'); for (const l of [1, 2, 3, 4, 5, 6, 7, 8, 9]) if (!S.save.badges.includes(l)) S.save.badges.push(l); tp(40, 5); await wait(0.4); await walk('up', 1.5); await wait(1.5); await clickBtn(/credits|Credits/i); await wait(7); await closePanels(); } },
    { t: T('Tour finished', 'Hết tour'), d: T('Everything you saw runs on real community data. Press ✕ to keep playing.', 'Mọi thứ chạy trên dữ liệu thật của cộng đồng. Bấm ✕ để chơi tiếp.'), run: async () => { box.classList.add('done'); await wait(6); } },
  ];

  async function run() {
    for (st.i = 0; st.i < steps.length && !st.stop; st.i++) {
      const s = steps[st.i]; st.skip = false;
      ui.step.textContent = `${st.i + 1}/${steps.length}`; ui.title.textContent = tx(s.t); say(s.d); ui.bar.style.width = `${(st.i / steps.length) * 100}%`;
      const guard = new Promise(r => setTimeout(r, 75000 / st.speed));
      try { await Promise.race([s.run(), guard]); } catch (e) { console.warn('[demo] step failed', s.t.en, e); }
      for (const k in input) input[k] = false;
      if (S.mode === 'quiz' && !st.stop) await quizAuto();   // a riddle opened by an NPC talk must be answered, Esc does not close it
      if (S.mode !== 'play' && !st.stop) await closePanels();
    }
    ui.bar.style.width = '100%';
    if (st.stop) { box.remove(); }
  }
  UI.setLang(new URLSearchParams(location.search).get('lang') === 'vi' ? 'vi' : lang()); UI.applyStaticText();
  startGame(defaultSave());
  setTimeout(run, 800);
}
